<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
        <IsPackable>false</IsPackable>
        <NoWarn>$(NoWarn),NU1701,NU1903</NoWarn>
    </PropertyGroup>

    <!-- Exclude the unnecessary tests to save Github Actions time -->
    <!-- WatsonTcp is the default channel, WebSocketSharp is optional, BinaryFormatter is .net8 only, Quic is .net9 only -->
    <ItemGroup>
        <Compile Remove="BinarySerializationTests.cs" />
        <Compile Remove="InvokerTests.cs" />
        <Compile Remove="InvokerTestsSafe.cs" />
        <Compile Remove="QuicHandshakeMessageTests.cs" />
        <Compile Remove="RpcTests_Quic.cs" />
        <Compile Remove="RpcTests_WatsonTcp.cs" />
        <Compile Remove="RpcTests_WebsocketSharp.cs" />
        <Compile Remove="RpcTests_WsClientWsharpServer.cs" />
        <Compile Remove="RpcTests_WsharpClientWsServer.cs" />
        <Compile Remove="SessionResumeTestsQuic.cs" />
    </ItemGroup>

    <!-- .NET 8.0 only: include BinaryFormatter and a small bunch of other tests -->
    <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
        <Compile Remove="*.cs" />
        <Compile Include="BinarySerializationTests.cs" />
        <Compile Include="SourceGeneratorTests.cs" />
    </ItemGroup>

    <!-- .NET 9.0 only: include Quic channel -->
    <ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' And '$(OS)' == 'Windows_NT' ">
        <Compile Include="QuicHandshakeMessageTests.cs" />
        <Compile Include="RpcTests_Quic.cs">
            <DependentUpon>RpcTests.cs</DependentUpon>
        </Compile>
        <Compile Include="SessionResumeTestsQuic.cs">
            <DependentUpon>SessionResumeTests.cs</DependentUpon>
        </Compile>
        <ProjectReference Include="..\CoreRemoting.Channels.Quic\CoreRemoting.Channels.Quic.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="DryIoc.MefAttributedModel.dll" Version="7.0.2" />
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.10" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
        <PackageReference Include="System.Runtime.Serialization.Formatters" Version="9.0.10" Condition="'$(TargetFramework)' == 'net8.0'" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CoreRemoting.Authentication.Oidc\CoreRemoting.Authentication.Oidc.csproj" />
      <ProjectReference Include="..\CoreRemoting.Authentication.JPake\CoreRemoting.Authentication.JPake.csproj" />
      <ProjectReference Include="..\CoreRemoting.Authentication.SecureRemotePassword\CoreRemoting.Authentication.SecureRemotePassword.csproj" />
      <ProjectReference Include="..\CoreRemoting.Channels.WebsocketSharp\CoreRemoting.Channels.WebsocketSharp.csproj" />
      <ProjectReference Include="..\CoreRemoting.Serialization.Binary\CoreRemoting.Serialization.Binary.csproj" />
      <ProjectReference Include="..\CoreRemoting.Serialization.Hyperion\CoreRemoting.Serialization.Hyperion.csproj" />
      <ProjectReference Include="..\CoreRemoting.Tests.ExternalTypes\CoreRemoting.Tests.ExternalTypes.csproj" />
      <ProjectReference Include="..\CoreRemoting\CoreRemoting.csproj" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CoreRemoting.SourceGenerators\CoreRemoting.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="DicTests_DryIoc.cs">
        <DependentUpon>DicTests.cs</DependentUpon>
      </Compile>
      <Compile Update="DicTests_Microsoft.cs">
        <DependentUpon>DicTests.cs</DependentUpon>
      </Compile>
      <Compile Update="RpcTests_NamedPipe.cs">
        <DependentUpon>RpcTests.cs</DependentUpon>
      </Compile>
      <Compile Update="RpcTests_NullChannel.cs">
        <DependentUpon>RpcTests.cs</DependentUpon>
      </Compile>
      <Compile Update="RpcTests_Websockets.cs">
        <DependentUpon>RpcTests.cs</DependentUpon>
      </Compile>
      <Compile Update="SessionResumeTestsNoEncryption.cs">
        <DependentUpon>SessionResumeTests.cs</DependentUpon>
      </Compile>
      <Compile Update="SessionResumeTestsWebSockets.cs">
        <DependentUpon>SessionResumeTests.cs</DependentUpon>
      </Compile>
      <Compile Update="SessionResumeTestsWsockNoEncr.cs">
        <DependentUpon>SessionResumeTests.cs</DependentUpon>
      </Compile>
      <Compile Update="SessionTests_Websockets.cs">
        <DependentUpon>SessionTests.cs</DependentUpon>
      </Compile>
    </ItemGroup>
    
    <ItemGroup>
      <None Update="TestConfig.xml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
