<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
        <RootNamespace>CoreRemoting.Authentication</RootNamespace>
        <AssemblyName>CoreRemoting.Authentication.Oidc</AssemblyName>
        <PackageVersion>1.0.0</PackageVersion>
        <Authors>Alexey Yakovlev</Authors>
        <Description>OpenID Connect (OIDC) authentication provider for CoreRemoting</Description>
        <Copyright>2018-2026 Alexey Yakovlev</Copyright>
        <PackageProjectUrl>https://github.com/theRainbird/CoreRemoting</PackageProjectUrl>
        <PackageLicenseUrl></PackageLicenseUrl>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>CoreRemoting.Authentication.Oidc</Title>
        <RepositoryUrl>https://github.com/theRainbird/CoreRemoting.git</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>Remoting RPC Network Authentication OIDC JWT</PackageTags>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <LangVersion>12</LangVersion>
        <NoWarn>$(NoWarn),NU1701,NU1903</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="CoreRemoting.Tests" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CoreRemoting\CoreRemoting.csproj" />
    </ItemGroup>

</Project>
